### ISSUE TITLE
headingDE2

### ISSUE THREAD

**Issue by arushton** [hrishiballal/airtraffic-data-protocol-development#15]
#### Described as:

headingDE2 | %d | 0 to 360 | Course over ground in centi-degrees

#### Issue:

Range is insufficient range for proposed unit.

#### Proposed resolution:

Either change the unit from centi-degrees to degrees or increase range from 0-360 -> 0-36000.

**Comment by hrishiballal** [comment]
Thank you, I have made the changes.
