### ISSUE TITLE
sourceGuid uppercase convention

### ISSUE THREAD

**Issue by arushton** [hrishiballal/airtraffic-data-protocol-development#17]
#### Described as:

Proposed value sourceGuid

#### Issue:

'sourceGuid' stands for "source Globally Unique Identifier", with the latter three word compressing the acronym the common 'GUID'; however, the 'uid' is referenced as lower case hence possible case concention issue.

#### Proposed resolution:

Change sourceGuid to sourceGUID

**Comment by hrishiballal** [comment]
Thank you for this, I have changed it across the document.
