### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by arushton** [hrishiballal/airtraffic-data-protocol-development#20]
#### Described as:

The legal status of the protocol.

#### Issue:

The airtraffic data protocol currently has no associated licence and as the intended purpose is to use as an open industry standard some kind of open source licence might be required.

#### Proposed resolution: 

Application of  BSD clause 2 or Apache License 2.0.

**Comment by hrishiballal** [comment]
This is a good question, do you have suggestions? We have used MIT and Apache license to some of the others.

**Comment by arushton** [comment]
I use BSD because it's clear and simple, but for a protocol it may need something more specific.

Is there someone within GUTMA we can ask?

**Comment by hrishiballal** [comment]
I think we will use Apache 2.0 since other GUTMA projects are using it as well.
