### ISSUE TITLE
Push vs Pull model of data

### ISSUE THREAD

**Issue by hrishiballal** [hrishiballal/airtraffic-data-protocol-development#3]
*Originally reported by* **Hrishikesh Ballal (Bitbucket: [hrishiballal](https://bitbucket.org/hrishiballal), GitHub: [hrishiballal](https://github.com/hrishiballal))**

----------------------------------------

Push Model vs Pull model:

* You can get all the traffic using GET and you can do that when you want
* Open UDP and every second you get data feed. 
* Push model: we send the data and 
* Pull model: I don’t want it every second ,but every 10 seconds. 
* Limit information send or received: Transmit mode  / receive mode.
* Most of sensors are push (real time tracking).  Some others have pull.  (90% are push since it is Ethernet device)

----------------------------------------
- Bitbucket: https://bitbucket.org/hrishiballal/airtraffic-data-protocol-development/issue/3

**Comment by vosst** [comment]
I agree, push vs. pull is rather a function and ability of the overall processing network, and you could easily switch between them with aggregator nodes that aggregate pushed observations. A common example is prometheus (used to monitor datacenter infrastructure at scale): it supports both push and pull and leaves it to the concrete use-case to take a proper decision.

**Comment by hrishiballal** [comment]
@vosst Thanks for this. I will add the Prometheus example link in the per their [FAQ](https://prometheus.io/docs/introduction/faq/#why-do-you-pull-rather-than-push?)
