### ISSUE TITLE
Add support for a new traffic source type

### ISSUE THREAD

**Issue by acasadoalonso** [hrishiballal/airtraffic-data-protocol-development#42]
Input from the FAI and OGN
======================
http://www.fai.org
http://www.glidernet.org

**Comment by acasadoalonso** [comment]
On the glider world we have a new source of traffic data and are the FLARMs/OGN trackers.
The Open Glider Network (OGN) collects all of that position data with more than 1000+ OGN stations and broadcast that thru their servers.

See the details on http://wiki.glidernet.org
See the traffic on   http://live.glidernet.map

We are willing to provide that data on the GUTMA Airtraffic Data protocol, however we need a new value for the traffic_source field, perhaps we can use the value 7 used as well as 2, or extend the definition to be hex and use the value A.

**Comment by acasadoalonso** [comment]
We can easily prepare a server that will broadcast the traffic information of the GUTMA Air traffic data protocol and it can be a good test bed of how to do it.

We will be happy to inject UAV traffic into our servers coming from some other platforms, that it will benefit our gliders/paragliders pilots.

**Comment by acasadoalonso** [comment]
Any feedback will be very welcome

**Comment by hrishiballal** [comment]
Hi @acasadoalonso Thank you for your comments and feedback. I really like the idea to do this test with you. Let us talk about it offline. 

At the moment, how do you want to change the traffic_source field? Should there be a 10 or 11 there to accommodate for a OGN server?

**Comment by acasadoalonso** [comment]
a value of 10 will be OK.
My email is acasado at acm.org

Fell free to contact me.
AC/.

**Comment by hrishiballal** [comment]
OK I have added it to the protocol.

**Comment by acasadoalonso** [comment]
I do not see it on the .md file

**Comment by hrishiballal** [comment]
Sorry I closed before I pushed the fix. It is now there!
