### ISSUE TITLE
Unmetered Connections/Metered Connections/IOT

### ISSUE THREAD

**Issue by hrishiballal** [hrishiballal/airtraffic-data-protocol-development#5]
*Originally reported by* **Craig McDermott (Bitbucket: [Craig_McDermott](https://bitbucket.org/Craig_McDermott), GitHub: Unknown)**

----------------------------------------

The JSON is somewhat verbose because it was created for an unmetered ethernet connection.  In the standard we need to consider metered connections and how to support them.  There are many options.  
* Most people like the verbose description of the data items but it should be on the table to look at less verbose JSON.  
* In the push model, we could just transmit the JSON delta's every second and then re-transmit the full message less frequently
*We could have more message types that have smaller data sets that could be selected
* etc etc etc

I believe the standard needs to address this as its own item.

----------------------------------------
- Bitbucket: https://bitbucket.org/hrishiballal/airtraffic-data-protocol-development/issue/5

**Comment by vosst** [comment]
Couldn't this be enabled and supported transparently on the transport level, e.g., by turning on compression for metered connections over an arbitrary transport?

**Comment by hrishiballal** [comment]
@vosst Yes agreed, transport shuold not be a part of this, we should just specify the fields and let the transport, compression etc. left to the manufacturer.
